### ISSUE TITLE
latest update is broken

### ISSUE THREAD

**Issue by jordandev** [SeaPea/GentleWake#1]
I get the App crashed! Message when opening Gentke Wake now after the new update.

On Pebble Steel. Tried deleting / readding and factory resetting so it looks like it's not a persist problem.

**Comment by SeaPea** [comment]
Yeah I have reverted the Pebble App Store to V2.1 . V2.2 is only crashing on Aplite and I am trying to debug, but the emulator is giving me no info. Sorry about the inconvenience. I am working on fixing it.

**Comment by SeaPea** [comment]
Found out it hit the memory limit of the Aplite Pebbles with all the new features in v2.2. Had to do a ton of refactoring and after lots of testing (sorry I didn't test on Aplite previously) it looks like v2.3 is working properly on all Pebbles. 

To make sure you have v2.3 you might have to uninstall Gentle Wake, remove it from the locker in the Pebble phone app and then add it again from the App Store. This will lose all the settings. Sorry for the inconvenience.

**Comment by jordandev** [comment]
Great thanks :)
