### ISSUE TITLE
Does smart monitoring require phone?

### ISSUE THREAD

**Issue by zaus** [SeaPea/GentleWake#10]
I've recently been enabling airplane mode on the pebble, and I think around the same time I noticed that the alarm always fires exactly on time rather than when I stir before.  Does it need the phone to analyze motion, or am I just sleeping really well?

**Comment by SeaPea** [comment]
Either you're a really sound sleeper or the Pebble OS has stopped sending accelerometer data to apps, which it does occasionally. In the latter case restarting your Pebbel should fix it.

**Comment by zaus** [comment]
I'll give restarting it a shot, thanks!  Great app!
