### ISSUE TITLE
Pebbles OG with 3.8 firmware have some problems

### ISSUE THREAD

**Issue by koolfy** [SeaPea/GentleWake#5]
Since the firmware update, pebble OGs have access to the time interface and 3.X SDK.

I think your app misdetects my Pebble OG as a Time or newer, thus
- The Main page displaying the time and next alarm has some formatting issues
- When setting an alarm, it will no be set to the right time, but will have some shifts depending on the user's timezone (from what I've seen)

it shouldn't be very hard to fix :)

see: https://developer.getpebble.com/guides/migration/3x-aplite-migration/

**Comment by SeaPea** [comment]
I think all I have to do is recompile with the 3.8 SDK, as those parts of Gentle Wake are controlled using SDK version defines. The current Apilte Gentle Wake PBW is still based on 2.x SDK so it is using 2.x code even when running on 3.8. But since 3.8 is still in beta I cannot release a recompiled version yet.

**Comment by koolfy** [comment]
That's fine :)

Just remember to be quick to the update when 3.8 goes public, or a lot of people west of GMT might get late to work a couple times :D 

Thanks for the app, by the way, it's been waking me up every morning for 3 months ;)

**Comment by koolfy** [comment]
It's out of beta and released now :)

Any news?

**Comment by koolfy** [comment]
Oh, just saw your latest commit, I guess you're at work :)
Thanks!

**Comment by SeaPea** [comment]
Alarms should work now and graphical glitches should be fixed. There is one case of crashing if you go into the Snooze Delay or Monitor Period and then go to set some alarms. For now, just exit the app between changing the settings and alarms.
